# ruff: noqa: E501,W291
"""
Add table answers.

Revision ID: f3e8d884e7fb
Revises:
Created: 2025-03-03 01:42:59.945627
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "f3e8d884e7fb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column(
            "received_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("question_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("choice", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("device_id", "question_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    # ### end Alembic commands ###
